name: gymtech
description: "A project that consist to automate a gym club."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2719.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gymtech_logo.png
  fonts:
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Light.ttf
          weight: 300
        - asset: assets/fonts/Teko-Regular.ttf
          weight: 400
        - asset: assets/fonts/Teko-Medium.ttf
          weight: 500
        - asset: assets/fonts/Teko-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Teko-Bold.ttf
          weight: 700