-- Création de la base de données
CREATE DATABASE IF NOT EXISTS gymtech;
USE gymtech;

-- Création de la table utilisateurs
CREATE TABLE IF NOT EXISTS utilisateurs (
  ID_USER INT AUTO_INCREMENT PRIMARY KEY,
  NOM_USER VARCHAR(50) NOT NULL,
  PRENOM_USER VARCHAR(50) NOT NULL,
  EMAIL_USER VARCHAR(255) NOT NULL UNIQUE,
  MOT_DE_PASSE_USER VARCHAR(255) NOT NULL,
  GENRE_USER ENUM('Homme', 'Femme', 'Autre') NOT NULL,
  DATE_NAISSANCE_USER DATE NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Index sur l'email
CREATE UNIQUE INDEX idx_email ON utilisateurs(EMAIL_USER);
